import json, os, time
src = open(os.path.join(os.path.dirname(os.path.abspath(__file__)), 'cdp.py')).read().replace('\nmain()\n', '\n')
ns = {'__file__': __file__}; exec(src, ns); c = ns['CDP']()
ev = lambda js: c.call('Runtime.evaluate', expression=js, awaitPromise=True, returnByValue=True)['result'].get('value')
c.call('Emulation.setDeviceMetricsOverride', width=390, height=844, deviceScaleFactor=2, mobile=True)
c.call('Emulation.setTouchEmulationEnabled', enabled=True, maxTouchPoints=5)
c.call('Page.navigate', url='http://localhost:8797/index.html'); time.sleep(7)
print('has-gyro', ev("document.documentElement.classList.contains('has-gyro')"), 'tip', ev("getComputedStyle(document.querySelector('.gyrotip')).display"))
ev("localStorage.clear(); document.querySelector('#startBtn').click(); 1"); time.sleep(1.5)
ev("__game.S.timers=[]; document.querySelector('#gyroBtn').click(); 1"); time.sleep(0.3)
def orient(a, b, g):
    c.call('DeviceOrientation.setDeviceOrientationOverride', alpha=a, beta=b, gamma=g); time.sleep(0.4)
    return ev("[+__game.S.yaw.toFixed(3), +__game.S.pitch.toFixed(3)]")
print('upright      ', orient(0, 90, 0))
print('turn right 30', orient(330, 90, 0))
print('tilt up 20   ', orient(330, 110, 0))
print('turn left 60 ', orient(30, 110, 0))
print('gyro on', ev("document.querySelector('#gyroBtn').classList.contains('on')"), 'sub', ev("document.querySelector('#subtitle').textContent"))
c.call('Page.captureScreenshot', format='png')
open('/tmp/claude-1000/-mnt-d--AI-GENERATED-------2026-horror/ade6b511-f646-4ef8-a52c-feaabe89190d/scratchpad/gyro.png', 'wb').write(__import__('base64').b64decode(c.call('Page.captureScreenshot', format='png')['data']))
# landscape phone: screen rotated 90
c.call('Emulation.setDeviceMetricsOverride', width=844, height=390, deviceScaleFactor=2, mobile=True, screenOrientation={'type': 'landscapePrimary', 'angle': 90})
time.sleep(1); ev("__game.S.yaw=0; __game.S.pitch=0; 1")
print('land base    ', orient(0, 0, -90))
print('land right 30', orient(330, 0, -90))
print('land up 20   ', orient(330, 0, -70))
print('err', ev("String(window.__err||'none')"))
c.call('DeviceOrientation.clearDeviceOrientationOverride')
c.call('Emulation.setTouchEmulationEnabled', enabled=False)
c.call('Emulation.clearDeviceMetricsOverride')
